version: "3"
services:
  redis:
    image: redis:latest
    restart: always
    container_name: redis-container
    ports:
      - "127.0.0.1:6379:6379"

  reader:
    build:
      context: .
    restart: unless-stopped
    container_name: reader-container
    command: ["python", "-u", "reader.py"]
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  writer:
    build:
      context: .
    restart: no
    container_name: writer-container
    command: ["python", "-u", "writer.py"]
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
